networks:
  yii2:
    name: yii2

services:
  nginx:
    container_name: yii2_nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./www:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - yii2
    depends_on:
      - php
  php:
    container_name: yii2_php
    build: ./images/php83fpm
    volumes:
      - ./www:/var/www/
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - yii2
    depends_on:
      - mysql
  mysql:
    container_name: yii2_mysql
    image: mysql:latest
    volumes:
      - ./www:/var/www
      - ./mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_USER=yii2
      - MYSQL_PASSWORD=yii2
      - MYSQL_ROOT_PASSWORD=yii2
      - MYSQL_DATABASE=yii2
    ports:
      - 3306:3306
    networks:
      - yii2